spring.application.name=RH

# Conexion a MySQL
spring.datasource.url=${URL}
spring.datasource.username=${NAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA - Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# COnfiguracion logging
logging.pattern.console=[%thread] %-5level: %logger{36} - %msg%n
logging.level.root=INFO
logging.level.gm.rh=INFO
logging.level.org.hibernate=WARN

# Spring Banner
spring.main.banner-mode=off